name: Provision t2.micro EC2

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_GIT_KEY: ${{ secrets.SSH_PRIVATE_GIT_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Create SSH key
        run: |
          sudo mkdir -p /home/ubuntu/.ssh
          sudo touch /home/ubuntu/.ssh/id_rsa
          echo "$SSH_PRIVATE_GIT_KEY" > /home/ubuntu/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: us-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          cd ./
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
